-- Users and Tasks schema for Supabase (PostgreSQL)
-- Run in Supabase SQL editor or via CLI

-- Enable required extensions (safe to run multiple times)
create extension if not exists "uuid-ossp";

-- USERS table
create table if not exists public.users (
  user_id integer generated by default as identity primary key,
  email text not null unique,
  full_name text not null,
  role text not null check (role in ('STAFF','MANAGER','DIRECTOR')),
  access_level integer not null check (access_level in (0,1,2)),
  created_at timestamptz not null default now()
);

-- PROJECTS table (create this BEFORE tasks table to avoid foreign key reference errors)
create table if not exists public.projects (
  project_id integer generated by default as identity primary key,
  name text not null,
  description text,
  end_date date, -- deadline
  owner_id integer references public.users(user_id) on delete set null,
  tasks integer[] default '{}', -- array of task IDs related to this project
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TASKS table
create table if not exists public.tasks (
  task_id integer generated by default as identity primary key,
  title text not null,
  description text,
  status text not null check (status in ('UNASSIGNED','ONGOING','UNDER_REVIEW','COMPLETED')) default 'UNASSIGNED',
  -- Priority bucket: integer 1–10 (1 = highest priority)
  priority_bucket integer not null check (priority_bucket between 1 and 10) default 5,
  due_date date,
  project text,
  owner_id integer references public.users(user_id) on delete set null,
  assignee_id integer references public.users(user_id) on delete set null,
  -- Note: column name kept as members_id per spec, stored as array to allow multiple members
  members_id integer[] default '{}',
  parent_task_id integer references public.tasks(task_id) on delete set null,
  attachments jsonb not null default '[]'::jsonb, -- e.g., [{"name":"spec.pdf","url":"..."}]
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safely add columns to tasks table if they don't exist
DO $$
BEGIN
    -- Add deleted_at column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'deleted_at') THEN
        ALTER TABLE public.tasks ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
    END IF;
    
    -- Add deleted_by column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'deleted_by') THEN
        ALTER TABLE public.tasks ADD COLUMN deleted_by INTEGER REFERENCES public.users(user_id);
    END IF;
    
    -- Add project_id column if it doesn't exist (NOW projects table exists)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'project_id') THEN
        ALTER TABLE public.tasks ADD COLUMN project_id integer references public.projects(project_id) on delete set null;
    END IF;
END $$;

-- Safely add owner_id column to projects table if it doesn't exist
DO $$
BEGIN
    -- Add owner_id column to projects if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'owner_id') THEN
        ALTER TABLE public.projects ADD COLUMN owner_id integer references public.users(user_id) on delete set null;
    END IF;
END $$;

-- Updated at trigger
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

-- Updated at trigger for projects
drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- Index for better performance
create index if not exists idx_tasks_project_id on public.tasks(project_id);
create index if not exists idx_projects_tasks on public.projects using gin(tasks);


-- ACTIVITY LOGS table
create table if not exists public.task_activity_logs (
  log_id integer generated by default as identity primary key,
  task_id integer not null references public.tasks(task_id) on delete cascade,
  author_id integer references public.users(user_id) on delete set null,
  type text not null check (type in (
    'status_changed',
    'field_edited',
    'comment_added',
    'reassigned',
    'task_created',
    'task_deleted',
    'task_restored'
  )),
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Indexes optimized for per-task chronological queries and filtering
create index if not exists idx_task_activity_logs_task_created_at on public.task_activity_logs(task_id, created_at);
create index if not exists idx_task_activity_logs_author on public.task_activity_logs(author_id);
create index if not exists idx_task_activity_logs_type on public.task_activity_logs(type);

 