-- Users and Tasks schema for Supabase (PostgreSQL)
-- Run in Supabase SQL editor or via CLI

-- Enable required extensions (safe to run multiple times)
create extension if not exists "uuid-ossp";

-- USERS table
create table if not exists public.users (
  user_id integer generated by default as identity primary key,
  email text not null unique,
  full_name text not null,
  role text not null check (role in ('STAFF','MANAGER','DIRECTOR')),
  access_level integer not null check (access_level in (0,1,2)),
  created_at timestamptz not null default now()
);

-- TASKS table
create table if not exists public.tasks (
  task_id integer generated by default as identity primary key,
  title text not null,
  description text,
  status text not null check (status in ('TO_DO','IN_PROGRESS','DONE')) default 'TO_DO',
  priority text not null check (priority in ('LOW','MEDIUM','HIGH')) default 'MEDIUM',
  due_date date,
  project text,
  owner_id integer references public.users(user_id) on delete set null,
  -- Note: column name kept as members_id per spec, stored as array to allow multiple members
  members_id integer[] default '{}',
  parent_task_id integer references public.tasks(task_id) on delete set null,
  attachments jsonb not null default '[]'::jsonb, -- e.g., [{"name":"spec.pdf","url":"..."}]
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Updated at trigger
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();


