-- Users and Tasks schema for Supabase (PostgreSQL)
-- Run in Supabase SQL editor or via CLI

-- Enable required extensions (safe to run multiple times)
create extension if not exists "uuid-ossp";

-- USERS table
create table if not exists public.users (
  user_id integer generated by default as identity primary key,
  email text not null unique,
  full_name text not null,
  role text not null check (role in ('STAFF','MANAGER','DIRECTOR')),
  access_level integer not null check (access_level in (0,1,2)),
  created_at timestamptz not null default now()
);

-- PROJECTS table (create this BEFORE tasks table to avoid foreign key reference errors)
create table if not exists public.projects (
  project_id integer generated by default as identity primary key,
  name text not null,
  description text,
  end_date date, -- deadline
  owner_id integer references public.users(user_id) on delete set null,
  tasks integer[] default '{}', -- array of task IDs related to this project
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TASKS table
create table if not exists public.tasks (
  task_id integer generated by default as identity primary key,
  title text not null,
  description text,
  status text not null check (status in ('UNASSIGNED','ONGOING','UNDER_REVIEW','COMPLETED')) default 'UNASSIGNED',
  -- Priority bucket: integer 1–10 (1 = highest priority)
  priority_bucket integer not null check (priority_bucket between 1 and 10) default 5,
  due_date date,
  project text,
  owner_id integer references public.users(user_id) on delete set null,
  assignee_id integer references public.users(user_id) on delete set null,
  -- Note: column name kept as members_id per spec, stored as array to allow multiple members
  members_id integer[] default '{}',
  parent_task_id integer references public.tasks(task_id) on delete set null,
  -- attachments jsonb not null default '[]'::jsonb, -- e.g., [{"name":"spec.pdf","url":"..."}]
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()

-- Add recurrence fields to tasks table
ALTER TABLE tasks ADD COLUMN is_recurring BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN recurrence_type VARCHAR(20) CHECK (recurrence_type IN ('daily', 'weekly', 'monthly', 'custom'));
ALTER TABLE tasks ADD COLUMN recurrence_interval INTEGER; -- For custom intervals (e.g., every 5 days)
ALTER TABLE tasks ADD COLUMN parent_recurring_task_id INTEGER REFERENCES tasks(task_id); -- Links instances to original template
ALTER TABLE tasks ADD COLUMN next_due_date DATE; -- When the next instance should be created
ALTER TABLE tasks ADD COLUMN recurrence_end_date DATE; -- Optional end date for recurrence

-- Add indexes for performance
CREATE INDEX idx_tasks_is_recurring ON tasks(is_recurring) WHERE is_recurring = TRUE;
CREATE INDEX idx_tasks_next_due_date ON tasks(next_due_date) WHERE next_due_date IS NOT NULL;
CREATE INDEX idx_tasks_parent_recurring ON tasks(parent_recurring_task_id) WHERE parent_recurring_task_id IS NOT NULL;
);

-- Safely add columns to tasks table if they don't exist
DO $$
BEGIN
    -- Add deleted_at column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'deleted_at') THEN
        ALTER TABLE public.tasks ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
    END IF;
    
    -- Add deleted_by column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'deleted_by') THEN
        ALTER TABLE public.tasks ADD COLUMN deleted_by INTEGER REFERENCES public.users(user_id);
    END IF;
    
    -- Add project_id column if it doesn't exist (NOW projects table exists)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'project_id') THEN
        ALTER TABLE public.tasks ADD COLUMN project_id integer references public.projects(project_id) on delete set null;
    END IF;
END $$;

-- Safely add owner_id column to projects table if it doesn't exist
DO $$
BEGIN
    -- Add owner_id column to projects if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'owner_id') THEN
        ALTER TABLE public.projects ADD COLUMN owner_id integer references public.users(user_id) on delete set null;
    END IF;
    
    -- Add members column to projects if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'members') THEN
        ALTER TABLE public.projects ADD COLUMN members integer[] default '{}';
    END IF;
END $$;

-- Updated at trigger
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

-- Updated at trigger for projects
drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- Index for better performance
create index if not exists idx_tasks_project_id on public.tasks(project_id);
create index if not exists idx_projects_tasks on public.projects using gin(tasks);


-- ACTIVITY LOGS table
create table if not exists public.task_activity_logs (
  log_id integer generated by default as identity primary key,
  task_id integer not null references public.tasks(task_id) on delete cascade,
  author_id integer references public.users(user_id) on delete set null,
  type text not null check (type in (
    'status_changed',
    'field_edited',
    'comment_added',
    'reassigned',
    'task_created',
    'task_deleted',
    'task_restored'
  )),
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Indexes optimized for per-task chronological queries and filtering
create index if not exists idx_task_activity_logs_task_created_at on public.task_activity_logs(task_id, created_at);
create index if not exists idx_task_activity_logs_author on public.task_activity_logs(author_id);
create index if not exists idx_task_activity_logs_type on public.task_activity_logs(type);

-- Add attachments table
CREATE TABLE task_attachments (
    attachment_id SERIAL PRIMARY KEY,
    task_id INTEGER NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size INTEGER NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    uploaded_by INTEGER NOT NULL REFERENCES users(user_id),
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes
CREATE INDEX idx_task_attachments_task_id ON task_attachments(task_id);
CREATE INDEX idx_task_attachments_uploaded_by ON task_attachments(uploaded_by);

-- Add HR role and team/department structure
DO $$
BEGIN
    -- Add HR to the role check constraint
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name = 'users' AND constraint_name = 'users_role_check') THEN
        ALTER TABLE public.users DROP CONSTRAINT users_role_check;
    END IF;
    
    ALTER TABLE public.users ADD CONSTRAINT users_role_check 
    CHECK (role IN ('STAFF','MANAGER','DIRECTOR','HR'));
    
    -- Update access_level check to include HR (level 3)
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name = 'users' AND constraint_name = 'users_access_level_check') THEN
        ALTER TABLE public.users DROP CONSTRAINT users_access_level_check;
    END IF;
    
    ALTER TABLE public.users ADD CONSTRAINT users_access_level_check 
    CHECK (access_level IN (0,1,2,3));
END $$;

-- Create departments table
CREATE TABLE IF NOT EXISTS public.departments (
  department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create teams table
CREATE TABLE IF NOT EXISTS public.teams (
  team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR(100) NOT NULL,
  department_id INTEGER REFERENCES public.departments(department_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(team_name, department_id) -- Team names must be unique within a department
);

-- Add team_id and department_id columns to users table
DO $$
BEGIN
    -- Add team_id column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'team_id') THEN
        ALTER TABLE public.users ADD COLUMN team_id INTEGER REFERENCES public.teams(team_id) ON DELETE SET NULL;
    END IF;
    
    -- Add department_id column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'department_id') THEN
        ALTER TABLE public.users ADD COLUMN department_id INTEGER REFERENCES public.departments(department_id) ON DELETE SET NULL;
    END IF;
END $$;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_team_id ON public.users(team_id);
CREATE INDEX IF NOT EXISTS idx_users_department_id ON public.users(department_id);
CREATE INDEX IF NOT EXISTS idx_teams_department_id ON public.teams(department_id);

-- Add task reminders table for automated reminder system
CREATE TABLE IF NOT EXISTS public.task_reminders (
  reminder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES public.tasks(task_id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  days_before INTEGER NOT NULL DEFAULT 3 CHECK (days_before IN (1, 3, 7)), -- How many days before due date to start reminders
  frequency_per_day INTEGER NOT NULL DEFAULT 1 CHECK (frequency_per_day BETWEEN 1 AND 3), -- How many times per day to remind (max 3)
  last_sent TIMESTAMPTZ, -- When last reminder was sent
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(task_id) -- One reminder setting per task
);

-- Track which reminders have been sent to avoid duplicates
CREATE TABLE IF NOT EXISTS public.reminder_log (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES public.tasks(task_id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  due_date DATE NOT NULL, -- The due date this reminder was for
  reminder_number INTEGER NOT NULL DEFAULT 1, -- Which reminder of the day (1, 2, or 3)
  days_before INTEGER NOT NULL, -- How many days before due date this was sent
  UNIQUE(task_id, user_id, due_date, reminder_number) -- Prevent duplicate reminders for same day/number
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_task_reminders_task_id ON public.task_reminders(task_id);
CREATE INDEX IF NOT EXISTS idx_task_reminders_enabled ON public.task_reminders(enabled) WHERE enabled = TRUE;
CREATE INDEX IF NOT EXISTS idx_reminder_log_task_user ON public.reminder_log(task_id, user_id);
CREATE INDEX IF NOT EXISTS idx_reminder_log_sent_at ON public.reminder_log(sent_at);

-- Add updated_at trigger for task_reminders
DROP TRIGGER IF EXISTS set_task_reminders_updated_at ON public.task_reminders;
CREATE TRIGGER set_task_reminders_updated_at
BEFORE UPDATE ON public.task_reminders
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--Notification display --
CREATE TABLE notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  task_id INTEGER REFERENCES tasks(task_id),
  message TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);